on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.12' 
        
    - uses: jpetrucciani/black-check@22.10.0
      with:
        path: ./
